location ^~ /project3/assets/ {
    alias /var/www/html/project3/assets/;
}

location ^~ /project3/ {
    root /var/www/html;
    index index.html;
    try_files $uri $uri/ /project3/index.html;
}

location = /project3 {
    return 301 /project3/;
}
